"""
Reports router — generate HTML and CSV compliance reports.
GET /api/reports/html → full HTML compliance report
GET /api/reports/csv  → CSV export of scan results
"""
import csv
import io
import json
from datetime import datetime
from typing import Optional

from fastapi import APIRouter, Depends, Query
from fastapi.responses import HTMLResponse, Response
from sqlalchemy.orm import Session

from core.database import get_db
from core.models import ScanSession, ScanResult, DeviceSnapshot

router = APIRouter(prefix="/api/reports", tags=["reports"])

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>HX-Guardian Compliance Report — {date}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 20px; color: #1a1a2e; }}
  h1 {{ color: #0f3460; border-bottom: 3px solid #e94560; padding-bottom: 10px; }}
  h2 {{ color: #16213e; margin-top: 30px; }}
  .score-box {{ display: inline-block; padding: 20px 40px; border-radius: 8px; font-size: 2em; font-weight: bold; margin: 10px 0; }}
  .green {{ background: #d4edda; color: #155724; }}
  .yellow {{ background: #fff3cd; color: #856404; }}
  .red {{ background: #f8d7da; color: #721c24; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 0.9em; }}
  th {{ background: #0f3460; color: white; padding: 8px 12px; text-align: left; }}
  td {{ padding: 7px 12px; border-bottom: 1px solid #dee2e6; }}
  tr:nth-child(even) {{ background: #f8f9fa; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.8em; font-weight: bold; }}
  .PASS {{ background: #d4edda; color: #155724; }}
  .FAIL {{ background: #f8d7da; color: #721c24; }}
  .NOT_APPLICABLE {{ background: #e2e3e5; color: #383d41; }}
  .MDM_REQUIRED {{ background: #cce5ff; color: #004085; }}
  .EXEMPT {{ background: #fff3cd; color: #856404; }}
  .ERROR {{ background: #f5c6cb; color: #721c24; }}
  .summary-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin: 20px 0; }}
  .summary-card {{ background: #f8f9fa; border: 1px solid #dee2e6; border-radius: 8px; padding: 15px; text-align: center; }}
  .summary-card .number {{ font-size: 2em; font-weight: bold; }}
  @media print {{ .no-print {{ display: none; }} }}
</style>
</head>
<body>
<h1>HX-Guardian Security Compliance Report</h1>
<p><strong>Generated:</strong> {date} &nbsp;&nbsp; <strong>Device:</strong> {device_model} ({os_version})</p>
<p><strong>Scan Session:</strong> #{session_id} — {triggered_by} scan on {scan_date}</p>

<h2>Overall Compliance Score</h2>
<div class="score-box {score_class}">{score_pct}%</div>

<div class="summary-grid">
  <div class="summary-card"><div class="number" style="color:#155724">{pass_count}</div><div>PASS</div></div>
  <div class="summary-card"><div class="number" style="color:#721c24">{fail_count}</div><div>FAIL</div></div>
  <div class="summary-card"><div class="number" style="color:#856404">{exempt_count}</div><div>EXEMPT</div></div>
  <div class="summary-card"><div class="number" style="color:#383d41">{na_count}</div><div>N/A</div></div>
  <div class="summary-card"><div class="number" style="color:#004085">{mdm_count}</div><div>MDM Required</div></div>
  <div class="summary-card"><div class="number">{total_rules}</div><div>Total Rules</div></div>
</div>

<h2>Device Status</h2>
<table>
  <tr><th>Check</th><th>Status</th></tr>
  <tr><td>SIP (System Integrity Protection)</td><td>{sip}</td></tr>
  <tr><td>FileVault Encryption</td><td>{filevault}</td></tr>
  <tr><td>Gatekeeper</td><td>{gatekeeper}</td></tr>
  <tr><td>Firewall</td><td>{firewall}</td></tr>
  <tr><td>Secure Boot</td><td>{secure_boot}</td></tr>
</table>

<h2>Results by Category</h2>
{category_table}

<h2>All Rule Results</h2>
{results_table}

<p style="margin-top:40px; color:#666; font-size:0.8em;">
  Generated by HX-Guardian Security Dashboard. This report is confidential.
  <br>Report generated at {date} UTC.
</p>
</body>
</html>"""


def _score_class(score: float) -> str:
    if score >= 90:
        return "green"
    elif score >= 70:
        return "yellow"
    return "red"


def _status_badge(status: str) -> str:
    return f'<span class="badge {status}">{status}</span>'


@router.get("/html", response_class=HTMLResponse)
def generate_html_report(
    session_id: Optional[int] = Query(None),
    db: Session = Depends(get_db),
):
    if not session_id:
        latest = (
            db.query(ScanSession)
            .filter(ScanSession.finished_at.isnot(None))
            .order_by(ScanSession.started_at.desc())
            .first()
        )
        if not latest:
            return HTMLResponse("<h1>No completed scans found. Run a full scan first.</h1>", status_code=404)
        session_id = latest.id

    session = db.query(ScanSession).filter(ScanSession.id == session_id).first()
    if not session:
        return HTMLResponse("<h1>Session not found</h1>", status_code=404)

    results = (
        db.query(ScanResult)
        .filter(ScanResult.session_id == session_id)
        .order_by(ScanResult.category, ScanResult.rule)
        .all()
    )

    # Category summary
    cat_map: dict[str, dict] = {}
    for r in results:
        cat = r.category or "Other"
        if cat not in cat_map:
            cat_map[cat] = {"pass": 0, "fail": 0, "na": 0, "mdm": 0, "exempt": 0, "error": 0}
        cat_map[cat][r.status.lower().replace("_required", "").replace("not_applicable", "na")] += 1

    category_rows = "".join(
        f"<tr><td>{cat}</td>"
        f"<td style='color:#155724'>{d['pass']}</td>"
        f"<td style='color:#721c24'>{d['fail']}</td>"
        f"<td>{d.get('na', 0)}</td>"
        f"<td style='color:#856404'>{d.get('exempt', 0)}</td>"
        f"<td style='color:#004085'>{d.get('mdm', 0)}</td></tr>"
        for cat, d in sorted(cat_map.items())
    )
    category_table = (
        "<table><tr><th>Category</th><th>PASS</th><th>FAIL</th><th>N/A</th><th>EXEMPT</th><th>MDM</th></tr>"
        + category_rows + "</table>"
    )

    result_rows = "".join(
        f"<tr><td>{r.rule}</td><td>{r.category}</td><td>{_status_badge(r.status)}</td>"
        f"<td>{r.result_value or ''}</td><td>{r.expected_value or ''}</td></tr>"
        for r in results
    )
    results_table = (
        "<table><tr><th>Rule</th><th>Category</th><th>Status</th><th>Result</th><th>Expected</th></tr>"
        + result_rows + "</table>"
    )

    # Device snapshot
    snapshot = (
        db.query(DeviceSnapshot)
        .order_by(DeviceSnapshot.captured_at.desc())
        .first()
    )
    sip = "✓ Enabled" if snapshot and snapshot.sip_enabled else "✗ Disabled"
    filevault = "✓ On" if snapshot and snapshot.filevault_on else "✗ Off"
    gatekeeper = "✓ Enabled" if snapshot and snapshot.gatekeeper_on else "✗ Disabled"
    firewall = "✓ On" if snapshot and snapshot.firewall_on else "✗ Off"
    secure_boot = snapshot.secure_boot if snapshot else "unknown"
    os_version = snapshot.os_version if snapshot else "unknown"
    hw_model = snapshot.hardware_model if snapshot else "unknown"

    score = session.score_pct or 0.0
    html = _HTML_TEMPLATE.format(
        date=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        device_model=hw_model,
        os_version=os_version,
        session_id=session.id,
        triggered_by=session.triggered_by,
        scan_date=session.started_at.strftime("%Y-%m-%d %H:%M UTC") if session.started_at else "",
        score_pct=round(score, 1),
        score_class=_score_class(score),
        pass_count=session.pass_count,
        fail_count=session.fail_count,
        na_count=session.na_count,
        exempt_count=session.exempt_count,
        mdm_count=session.mdm_count,
        total_rules=session.total_rules,
        sip=sip, filevault=filevault, gatekeeper=gatekeeper,
        firewall=firewall, secure_boot=secure_boot,
        category_table=category_table,
        results_table=results_table,
    )
    return HTMLResponse(html)


@router.get("/csv")
def export_results_csv(
    session_id: Optional[int] = Query(None),
    db: Session = Depends(get_db),
):
    if not session_id:
        latest = (
            db.query(ScanSession)
            .filter(ScanSession.finished_at.isnot(None))
            .order_by(ScanSession.started_at.desc())
            .first()
        )
        if not latest:
            return Response("No completed scans", media_type="text/plain", status_code=404)
        session_id = latest.id

    results = (
        db.query(ScanResult)
        .filter(ScanResult.session_id == session_id)
        .order_by(ScanResult.category, ScanResult.rule)
        .all()
    )

    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["rule", "category", "status", "result_value", "expected_value",
                     "message", "scanned_at", "duration_ms"])
    for r in results:
        writer.writerow([
            r.rule, r.category, r.status,
            r.result_value or "", r.expected_value or "",
            r.message or "",
            r.scanned_at.isoformat() if r.scanned_at else "",
            r.duration_ms or "",
        ])

    return Response(
        content=output.getvalue(),
        media_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename=hxguardian_scan_{session_id}.csv"},
    )
